# Generated by Django 3.1.4 on 2020-12-10 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo del apartado')),
                ('startdate', models.DateField(verbose_name='Fecha de inicio')),
                ('finaldate', models.DateField(verbose_name='Fecha de liquidacion')),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('total', models.CharField(max_length=150, verbose_name='Total a pagar')),
            ],
            options={
                'verbose_name': 'Apartado',
                'verbose_name_plural': 'Apartados',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo de Ctegoria')),
                ('name', models.CharField(max_length=10, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo del Cliente')),
                ('firstname', models.CharField(max_length=80, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=80, verbose_name='Apellidos(s)')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('direction', models.CharField(max_length=100, verbose_name='direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo de empleado')),
                ('name', models.CharField(max_length=90, verbose_name='Nombre de empleado')),
                ('password', models.CharField(max_length=6, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo del proveedor')),
                ('firstname', models.CharField(max_length=80, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=80, verbose_name='Apellidos(s)')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('direction', models.CharField(max_length=100, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo del Telefono')),
                ('phone', models.CharField(max_length=15, verbose_name='Numero telefonico')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Codigo de Venta')),
                ('date', models.DateField(verbose_name='Fecha de venta')),
                ('time', models.TimeField(max_length=200, unique=True, verbose_name='Hora')),
                ('total', models.CharField(max_length=150, verbose_name='Total a pagar')),
                ('id_employee', models.CharField(max_length=100, unique=True, verbose_name='Id empleado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo del producto')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca del producto')),
                ('description', models.CharField(max_length=150, verbose_name='Descripcion del producto')),
                ('saleExistence', models.PositiveIntegerField(verbose_name='Existencia en venta')),
                ('cellarExistence', models.PositiveIntegerField(verbose_name='Existencia en bodega')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
