# Generated by Django 3.1.4 on 2020-12-10 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20201210_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartado',
            name='Empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.empleado'),
            preserve_default=False,
        ),
    ]
