# Generated by Django 3.1.4 on 2020-12-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_apartado_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo de Ctegoria')),
                ('name', models.CharField(max_length=10, verbose_name='Categoria')),
                ('totalcantifad', models.CharField(max_length=30, verbose_name='total a pagar')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.RemoveField(
            model_name='apartado',
            name='Empleado',
        ),
    ]
