# Generated by Django 3.1.4 on 2020-12-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20201210_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparece',
            options={'verbose_name': 'Aparece', 'verbose_name_plural': 'Aparecen'},
        ),
        migrations.RenameField(
            model_name='aparece',
            old_name='totalcantifad',
            new_name='totalcantidad',
        ),
        migrations.RemoveField(
            model_name='aparece',
            name='name',
        ),
        migrations.AlterField(
            model_name='aparece',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Codigo de barra'),
        ),
    ]
