# Generated by Django 3.1.4 on 2020-12-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20201210_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aparece',
        ),
    ]
