# Generated by Django 3.1.4 on 2020-12-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_delete_aparece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=58, verbose_name='Categoria'),
        ),
    ]
