# Generated by Django 3.1.4 on 2020-12-11 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_apartado_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartado',
            name='empleados',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.empleado'),
            preserve_default=False,
        ),
    ]
