# Generated by Django 3.1.4 on 2020-12-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_venta_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo del Telefono')),
                ('barcode', models.CharField(max_length=15, verbose_name='Codigo de barra')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
    ]
