# Generated by Django 3.1.4 on 2020-12-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_tiene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo de ID')),
                ('barcode', models.CharField(max_length=15, verbose_name='Codigo de barra')),
                ('cantidadxpro', models.CharField(max_length=30, verbose_name='Cantida total')),
            ],
            options={
                'verbose_name': 'Aparece',
                'verbose_name_plural': 'Aparecen',
            },
        ),
        migrations.AlterModelOptions(
            name='tiene',
            options={'verbose_name': 'Codigo de barra', 'verbose_name_plural': 'Codigo de barras'},
        ),
    ]
