# Generated by Django 3.1.4 on 2020-12-12 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_auto_20201211_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparece',
            name='ventas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.venta'),
            preserve_default=False,
        ),
    ]
