# Generated by Django 3.1.4 on 2020-12-12 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_producto_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiene',
            name='apartados',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.apartado'),
            preserve_default=False,
        ),
    ]
